# This workflow will build Angular project1

name: Build and Deploy Angular on Windows

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./Frontend

      - name: Build Angular app
        run: npm run build -- --configuration production
        working-directory: ./Frontend

      - name: Deploy Angular app to IIS folder
        run: |
          $source = "dist\<your-angular-project-name>\*"
          $destination = "E:\WEBRoot\kpilcangulargithub"
          if (!(Test-Path $destination)) {
            New-Item -ItemType Directory -Path $destination
          }
          Copy-Item $source $destination -Recurse -Force
